# Generated by Django 4.0.1 on 2023-10-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
